### ISSUE TITLE
a few suggestion for the library

### ISSUE THREAD

**Issue by daya-pangestu** [derysudrajat/EasyAdapter#3]
thanks for the awesome library, 
althought i kinda see a few catch that may or may not become problem

1. method EasyListener#create only pass param parent, but not viewgroup
viewType can be used to provide multiple view for the same recylerview, by overrided getViewType and return the int resoruce of said layout, we can use viewType to diferentiate the layout , example
```
 override  fun getItemViewType(position : Int) : Int = 
  when(data[position]){
    is DataClassA -> R.layout.itemA
    is DataClassB -> R.layout.itemB
}

 override fun create(parent: ViewGroup,viewType : Int): ItemDataBinding {
      //viewType will be either R.layout.itemA or R.layout.itemB
     when(viewType){
         R.layout.itemA -> ItemABinding.inflate.......
         R.layout.itemB -> ItemBBinding.inflate.......
     }
}
```
2.setting onclickListener may become an issue
library provide method EasyListener#onBind that contain param viewBinding, and current item, its only natural to set a clickListener inside EasyListener#onBind method, but because EasyListener#onBind invoked inside Recyclerview.OnBindViewHolder any onClickListener would become an expensive operation becuase Recyclerview.OnBindViewHolder always be called on every time a new item scrolls into view or on data change new  interface of View.Clicklistener was created.  i suggest to add new method in EasyListener that get invoked on Recyclerview.onCreateViewHolder or inside ViewHolder class that spesific only for clickListener maybe something like this : 

abstract class EasyAdapter<T, Binding : ViewBinding>(
    private val data: MutableList<T>,
) : RecyclerView.Adapter<EasyAdapter.ViewHolder>(), EasyListener<T, Binding> {

    class ViewHolder(view: View) : RecyclerView.ViewHolder(view)

    private lateinit var binding: Binding

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
        binding = create(parent)

        binding.itemView.setOnClickListener{
               handleClick(data[adapterPosition]) //guarantee to get created only once
        }
        return ViewHolder(binding.root)
    }

    override fun onBindViewHolder(holder: ViewHolder, position: Int) {
        onBind(binding, data[position])
    }

    override fun getItemCount(): Int = data.size

}

**Comment by derysudrajat** [comment]
Hello, @daya-pangestu thanks for the advice on this library,
- To provide multiple views in `EasyAdapter` now you can use `MultipleEasyAdapter`
- for `OnClickListener` inside `onCreateViewHolder` that not been provided yet, but if you want to contribute it that awesome check for the new update for this library
